version: 2

before:
  hooks:
    - go mod download
    
builds:
- 
  main: ./cmd/main.go
  ldflags:
      - -s -w -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - freebsd
  - windows
  - linux

  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
  goarch:
    - amd64
    - arm
    - arm64

archives:
- formats: [tar.gz]
  format_overrides:
    - goos: windows
      formats: [zip]
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
